server:
  forward-headers-strategy: native

spring:
  application:
    name: obrit-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PWD}
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
      region: ${S3_REGION}


obrit:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
